-- Idempotent Supabase/PostgreSQL schema. Run manually in the Supabase SQL editor.
-- Money is stored as integer minor units. This solo-studio schema has one calendar (no stylist table).
create extension if not exists btree_gist;

do $$ begin create type public.appointment_status as enum ('pending','confirmed','in_service','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('paid','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text, full_name text,
  role text not null default 'staff' check (role in ('staff','super_admin')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.system_settings (
  key text primary key check (btrim(key) <> ''), value jsonb not null,
  description text, updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key, name text not null check (btrim(name) <> ''), phone text not null,
  email text, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.services (
  id bigint generated by default as identity primary key, name text not null check (btrim(name) <> ''), duration_min integer not null check (duration_min > 0),
  price bigint not null check (price >= 0), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.products (
  id bigint generated by default as identity primary key, name text not null check (btrim(name) <> ''), price bigint not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0), vendor text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.appointments (
  id bigint generated by default as identity primary key, customer_id bigint not null references public.customers(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete restrict, start_time timestamptz not null, end_time timestamptz not null,
  status public.appointment_status not null default 'pending', total_amount bigint not null default 0 check (total_amount >= 0),
  custom_items jsonb not null default '[]'::jsonb check (jsonb_typeof(custom_items) = 'array'), note text, deleted_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (start_time < end_time)
);
create table if not exists public.blocked_times (
  id bigint generated by default as identity primary key, title text not null default 'Blocked', start_time timestamptz not null, end_time timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (start_time < end_time)
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key, appointment_id bigint not null unique references public.appointments(id) on delete restrict,
  idempotency_key text not null unique check (btrim(idempotency_key) <> ''), status public.order_status not null default 'paid',
  service_amount bigint not null check (service_amount >= 0), product_amount bigint not null check (product_amount >= 0), custom_amount bigint not null check (custom_amount >= 0),
  discount bigint not null default 0 check (discount >= 0), total_amount bigint not null check (total_amount >= 0), payment_method text not null check (payment_method in ('cash','line_pay')),
  custom_items jsonb not null default '[]'::jsonb check (jsonb_typeof(custom_items) = 'array'),
  voided_at timestamptz, void_reason text, created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key, order_id bigint not null references public.orders(id) on delete restrict,
  item_type text not null check (item_type in ('service','product','custom')), product_id bigint references public.products(id) on delete restrict,
  name text not null, quantity integer not null check (quantity > 0), unit_amount bigint not null check (unit_amount >= 0), line_amount bigint not null check (line_amount >= 0),
  check ((item_type = 'product') = (product_id is not null))
);
create table if not exists public.stock_adjustments (
  id bigint generated by default as identity primary key, product_id bigint not null references public.products(id) on delete restrict,
  order_id bigint references public.orders(id) on delete restrict, quantity_delta integer not null check (quantity_delta <> 0), resulting_stock integer not null check (resulting_stock >= 0),
  reason text not null, created_at timestamptz not null default now()
);
create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  category text not null check (btrim(category) <> ''), amount bigint not null check (amount >= 0),
  occurred_at timestamptz not null default now(), notes text,
  source text not null default 'manual' check (source in ('manual','appointment','order')),
  appointment_id bigint unique references public.appointments(id) on delete restrict,
  order_id bigint unique references public.orders(id) on delete restrict,
  voided_at timestamptz, void_reason text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check (source = 'manual' or appointment_id is not null)
);
insert into public.system_settings(key,value,description) values
  ('store_name',to_jsonb('我的美髮工作室'::text),'店家顯示名稱'),
  ('opening_time',to_jsonb('10:00'::text),'每日開始營業時間'),
  ('closing_time',to_jsonb('20:00'::text),'每日結束營業時間'),
  ('default_payment',to_jsonb('cash'::text),'預設付款方式：cash 或 line_pay'),
  ('holiday_surcharge_type',to_jsonb('none'::text),'假日加價方式'),
  ('holiday_surcharge_value',to_jsonb(0),'假日加價比例或固定金額'),
  ('reminder_enabled',to_jsonb(true),'是否啟用預約提醒'),
  ('reminder_hours',to_jsonb(24),'預約前提醒小時數'),
  ('auto_backup',to_jsonb(false),'自動備份偏好')
on conflict(key) do nothing;
-- Preserve optional fields used by existing deployments of the salon UI.
alter table public.customers add column if not exists email text;
alter table public.profiles add column if not exists full_name text;
alter table public.appointments add column if not exists deleted_at timestamptz;
alter table public.orders add column if not exists voided_at timestamptz;
alter table public.orders add column if not exists void_reason text;
alter table public.finance_records add column if not exists voided_at timestamptz;
alter table public.finance_records add column if not exists void_reason text;
create index if not exists appointments_customer_idx on public.appointments(customer_id, start_time desc);
create index if not exists appointments_service_idx on public.appointments(service_id);
create index if not exists appointments_start_idx on public.appointments(start_time);
create index if not exists appointments_active_idx on public.appointments(start_time) where deleted_at is null;
create index if not exists blocked_times_start_idx on public.blocked_times(start_time);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists stock_adjustments_product_idx on public.stock_adjustments(product_id, created_at desc);
create index if not exists finance_records_occurred_idx on public.finance_records(occurred_at desc);
create index if not exists finance_records_type_occurred_idx on public.finance_records(type, occurred_at desc);
create index if not exists orders_active_idx on public.orders(appointment_id) where voided_at is null;
create index if not exists finance_records_active_occurred_idx on public.finance_records(occurred_at desc) where voided_at is null;
alter table public.appointments drop constraint if exists appointments_no_active_overlap;
alter table public.appointments add constraint appointments_no_active_overlap exclude using gist (tstzrange(start_time,end_time,'[)') with &&) where (status <> 'cancelled' and deleted_at is null);
do $$ begin alter table public.blocked_times add constraint blocked_times_no_overlap exclude using gist (tstzrange(start_time,end_time,'[)') with &&); exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = pg_catalog, public as $$ begin new.updated_at = now(); return new; end $$;
create or replace function public.handle_new_user_profile() returns trigger language plpgsql security definer set search_path = pg_catalog, public as $$
declare v_role text;
begin
  perform pg_advisory_xact_lock(8127332);
  v_role:=case when exists(select 1 from public.profiles where role='super_admin') then 'staff' else 'super_admin' end;
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,nullif(btrim(coalesce(new.raw_user_meta_data->>'full_name','')),''),v_role)
  on conflict(id) do update set email=excluded.email,full_name=coalesce(public.profiles.full_name,excluded.full_name),updated_at=now();
  return new;
end $$;
create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path = pg_catalog, public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='super_admin');
$$;
revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to authenticated;
create or replace function public.sync_completed_appointment_income() returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_order_id bigint; v_amount bigint; v_payment_method text; v_notes text;
begin
  if new.status <> 'completed' then return new; end if;
  select o.id,o.total_amount,o.payment_method into v_order_id,v_amount,v_payment_method from public.orders o where o.appointment_id=new.id;
  v_amount:=coalesce(v_amount,new.total_amount);
  v_notes:=case when v_payment_method='cash' then '現金' when v_payment_method is null then '預約完成自動入帳' else 'LINE Pay' end;
  insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
  values ('income','服務／產品銷售',v_amount,new.start_time,v_notes,case when v_order_id is null then 'appointment' else 'order' end,new.id,v_order_id)
  on conflict (appointment_id) do update set amount=excluded.amount,occurred_at=excluded.occurred_at,notes=excluded.notes,order_id=coalesce(excluded.order_id,public.finance_records.order_id),source=excluded.source,updated_at=now();
  return new;
end $$;
create or replace function public.sync_order_income() returns trigger language plpgsql set search_path = pg_catalog, public as $$
declare v_start_time timestamptz; v_notes text;
begin
  select start_time into strict v_start_time from public.appointments where id=new.appointment_id;
  v_notes:=case new.payment_method when 'cash' then '現金' else 'LINE Pay' end;
  insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
  values ('income','服務／產品銷售',new.total_amount,v_start_time,v_notes,'order',new.appointment_id,new.id)
  on conflict (appointment_id) do update set amount=excluded.amount,occurred_at=excluded.occurred_at,notes=excluded.notes,order_id=excluded.order_id,source='order',updated_at=now();
  return new;
end $$;
create or replace function public.validate_calendar_slot() returns trigger language plpgsql set search_path = pg_catalog, public as $$
begin
  perform pg_advisory_xact_lock(8127331);
  if tg_table_name = 'appointments' then
    if new.status <> 'cancelled' and exists (
      select 1 from public.blocked_times b where new.start_time < b.end_time and new.end_time > b.start_time
    ) then raise exception using errcode='23P01', message='Appointment overlaps blocked time'; end if;
  elsif tg_table_name = 'blocked_times' then
    if exists (
      select 1 from public.appointments a where a.status <> 'cancelled' and a.deleted_at is null and new.start_time < a.end_time and new.end_time > a.start_time
    ) then raise exception using errcode='23P01', message='Blocked time overlaps appointment'; end if;
  end if;
  return new;
end $$;
create or replace function public.validate_appointment_transition() returns trigger language plpgsql set search_path = pg_catalog, public as $$
begin
  if tg_op='INSERT' then
    if new.status<>'pending' then raise exception using errcode='23514', message='New appointments must start pending'; end if;
    return new;
  end if;
  if old.status = new.status then return new; end if;
  if old.status in ('completed','cancelled') then raise exception using errcode='23514', message='Terminal appointment status cannot be changed'; end if;
  if not ((old.status='pending' and new.status in ('confirmed','cancelled')) or (old.status='confirmed' and new.status in ('in_service','cancelled')) or (old.status='in_service' and new.status='cancelled') or (old.status='in_service' and new.status='completed' and current_setting('app.checkout_appointment_id',true)=new.id::text)) then
    raise exception using errcode='23514', message='Invalid appointment state transition; completion requires checkout';
  end if; return new;
end $$;

drop trigger if exists auth_user_profile_created on auth.users; create trigger auth_user_profile_created after insert or update of email on auth.users for each row execute function public.handle_new_user_profile();
insert into public.profiles(id,email,full_name,role)
select id,email,nullif(btrim(coalesce(raw_user_meta_data->>'full_name','')),''),'staff' from auth.users
on conflict(id) do update set email=excluded.email,full_name=coalesce(public.profiles.full_name,excluded.full_name),updated_at=now();
with first_user as (select id from auth.users order by created_at,id limit 1)
update public.profiles set role='super_admin',updated_at=now()
where id=(select id from first_user) and not exists(select 1 from public.profiles where role='super_admin');
drop trigger if exists profiles_updated_at on public.profiles; create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists system_settings_updated_at on public.system_settings; create trigger system_settings_updated_at before update on public.system_settings for each row execute function public.set_updated_at();
drop trigger if exists customers_updated_at on public.customers; create trigger customers_updated_at before update on public.customers for each row execute function public.set_updated_at();
drop trigger if exists services_updated_at on public.services; create trigger services_updated_at before update on public.services for each row execute function public.set_updated_at();
drop trigger if exists products_updated_at on public.products; create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists appointments_updated_at on public.appointments; create trigger appointments_updated_at before update on public.appointments for each row execute function public.set_updated_at();
drop trigger if exists blocked_times_updated_at on public.blocked_times; create trigger blocked_times_updated_at before update on public.blocked_times for each row execute function public.set_updated_at();
drop trigger if exists finance_records_updated_at on public.finance_records; create trigger finance_records_updated_at before update on public.finance_records for each row execute function public.set_updated_at();
drop trigger if exists orders_sync_income on public.orders; create trigger orders_sync_income after insert or update of total_amount,payment_method on public.orders for each row execute function public.sync_order_income();
drop trigger if exists appointments_sync_income on public.appointments; create trigger appointments_sync_income after insert or update of status,total_amount,start_time on public.appointments for each row when (new.status = 'completed') execute function public.sync_completed_appointment_income();
drop trigger if exists appointments_slot_guard on public.appointments; create trigger appointments_slot_guard before insert or update of start_time,end_time,status on public.appointments for each row execute function public.validate_calendar_slot();
drop trigger if exists blocks_slot_guard on public.blocked_times; create trigger blocks_slot_guard before insert or update of start_time,end_time on public.blocked_times for each row execute function public.validate_calendar_slot();
drop trigger if exists appointment_state_guard on public.appointments; create trigger appointment_state_guard before insert or update on public.appointments for each row execute function public.validate_appointment_transition();

-- Backfill one ledger row per existing completed order without double-counting reruns.
insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
select 'income','服務／產品銷售',o.total_amount,a.start_time,
  case o.payment_method when 'cash' then '現金' else 'LINE Pay' end,
  'order',a.id,o.id
from public.orders o join public.appointments a on a.id=o.appointment_id
where a.status='completed'
on conflict (appointment_id) do update set amount=excluded.amount,occurred_at=excluded.occurred_at,notes=excluded.notes,order_id=excluded.order_id,source='order',updated_at=now();

create or replace function public.create_appointment(p_customer_id bigint,p_service_id bigint,p_start_time timestamptz,p_status text default 'pending',p_custom_items jsonb default '[]',p_note text default null)
returns public.appointments language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_duration integer; v_price bigint; v_result public.appointments;
begin
  if p_status <> 'pending' then raise exception 'New appointments must start pending'; end if;
  select duration_min,price into strict v_duration,v_price from public.services where id=p_service_id and active;
  insert into public.appointments(customer_id,service_id,start_time,end_time,status,total_amount,custom_items,note)
  values(p_customer_id,p_service_id,p_start_time,p_start_time+make_interval(mins=>v_duration),'pending',v_price,coalesce(p_custom_items,'[]'),p_note) returning * into v_result;
  return v_result;
end $$;
create or replace function public.update_appointment(p_id bigint,p_customer_id bigint,p_service_id bigint,p_start_time timestamptz,p_status text,p_custom_items jsonb default '[]',p_note text default null)
returns public.appointments language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_duration integer; v_result public.appointments;
begin
  select duration_min into strict v_duration from public.services where id=p_service_id;
  update public.appointments set customer_id=p_customer_id,service_id=p_service_id,start_time=p_start_time,end_time=p_start_time+make_interval(mins=>v_duration),status=p_status::public.appointment_status,custom_items=coalesce(p_custom_items,'[]'),note=p_note where id=p_id returning * into strict v_result;
  return v_result;
end $$;
create or replace function public.adjust_product_stock(p_product_id bigint,p_quantity_delta integer,p_reason text) returns integer
language plpgsql security invoker set search_path = pg_catalog, public as $$ declare v_stock integer; begin
  if p_quantity_delta=0 or btrim(p_reason)='' then raise exception 'A non-zero delta and reason are required'; end if;
  update public.products set stock=stock+p_quantity_delta where id=p_product_id and stock+p_quantity_delta>=0 returning stock into v_stock;
  if not found then raise exception 'Product missing or insufficient stock'; end if;
  insert into public.stock_adjustments(product_id,quantity_delta,resulting_stock,reason) values(p_product_id,p_quantity_delta,v_stock,p_reason); return v_stock;
end $$;
create or replace function public.update_product(p_product_id bigint,p_name text,p_price bigint,p_stock integer,p_vendor text default null,p_active boolean default true)
returns integer language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_previous integer; v_delta integer;
begin
  if btrim(coalesce(p_name,''))='' or p_price<0 or p_stock<0 then raise exception 'Invalid product values'; end if;
  select stock into strict v_previous from public.products where id=p_product_id for update;
  update public.products set name=btrim(p_name),price=p_price,stock=p_stock,vendor=nullif(btrim(coalesce(p_vendor,'')),''),active=p_active where id=p_product_id;
  v_delta:=p_stock-v_previous;
  if v_delta<>0 then insert into public.stock_adjustments(product_id,quantity_delta,resulting_stock,reason) values(p_product_id,v_delta,p_stock,'Inline stock edit'); end if;
  return p_stock;
end $$;
create or replace function public.checkout_appointment(p_appointment_id bigint,p_idempotency_key text,p_product_items jsonb default '[]',p_custom_items jsonb default '[]',p_payment_method text default 'cash',p_discount bigint default 0)
returns table(order_id bigint,total_amount bigint) language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_app public.appointments; v_order public.orders; v_service_name text; v_service_amount bigint; v_product_amount bigint:=0; v_custom_amount bigint:=0; v_item jsonb; v_product public.products; v_qty integer; v_total bigint;
begin
  -- Lock first so concurrent retries serialize before checking the idempotency record.
  select * into strict v_app from public.appointments where id=p_appointment_id for update;
  select * into v_order from public.orders where idempotency_key=p_idempotency_key;
  if found then if v_order.appointment_id<>p_appointment_id then raise exception 'Idempotency key already used'; end if; return query select v_order.id,v_order.total_amount; return; end if;
  if exists(select 1 from public.orders where appointment_id=p_appointment_id) then raise exception 'Appointment was already checked out with another idempotency key'; end if;
  if v_app.status<>'in_service' then raise exception 'Only in-service appointments can be checked out'; end if;
  select name,price into strict v_service_name,v_service_amount from public.services where id=v_app.service_id;
  if jsonb_typeof(coalesce(p_product_items,'[]'))<>'array' or jsonb_typeof(coalesce(p_custom_items,'[]'))<>'array' or p_discount<0 or p_payment_method not in ('cash','line_pay') then raise exception 'Invalid checkout items, discount, or payment method'; end if;
  for v_item in select value from jsonb_array_elements(coalesce(p_product_items,'[]')) loop
    v_qty=(v_item->>'quantity')::integer; if v_qty<=0 then raise exception 'Product quantity must be positive'; end if;
    select * into strict v_product from public.products where id=(v_item->>'product_id')::bigint for update;
    if not v_product.active or v_product.stock<v_qty then raise exception 'Product unavailable or insufficient stock'; end if;
    v_product_amount:=v_product_amount+(v_product.price*v_qty);
  end loop;
  for v_item in select value from jsonb_array_elements(coalesce(p_custom_items,'[]')) loop
    if btrim(coalesce(v_item->>'name',''))='' or (v_item->>'amount')::bigint<0 then raise exception 'Invalid custom item'; end if; v_custom_amount:=v_custom_amount+(v_item->>'amount')::bigint;
  end loop;
  v_total:=greatest(0,v_service_amount+v_product_amount+v_custom_amount-p_discount);
  insert into public.orders(appointment_id,idempotency_key,service_amount,product_amount,custom_amount,discount,total_amount,payment_method,custom_items) values(p_appointment_id,p_idempotency_key,v_service_amount,v_product_amount,v_custom_amount,p_discount,v_total,p_payment_method,coalesce(p_custom_items,'[]')) returning * into v_order;
  insert into public.order_items(order_id,item_type,name,quantity,unit_amount,line_amount) values(v_order.id,'service',v_service_name,1,v_service_amount,v_service_amount);
  for v_item in select value from jsonb_array_elements(coalesce(p_product_items,'[]')) loop
    v_qty=(v_item->>'quantity')::integer; select * into strict v_product from public.products where id=(v_item->>'product_id')::bigint for update;
    update public.products set stock=stock-v_qty where id=v_product.id and active and stock>=v_qty returning stock into v_product.stock;
    if not found then raise exception 'Product unavailable or insufficient stock'; end if;
    insert into public.order_items(order_id,item_type,product_id,name,quantity,unit_amount,line_amount) values(v_order.id,'product',v_product.id,v_product.name,v_qty,v_product.price,v_product.price*v_qty);
    insert into public.stock_adjustments(product_id,order_id,quantity_delta,resulting_stock,reason) values(v_product.id,v_order.id,-v_qty,v_product.stock,'Checkout');
  end loop;
  for v_item in select value from jsonb_array_elements(coalesce(p_custom_items,'[]')) loop insert into public.order_items(order_id,item_type,name,quantity,unit_amount,line_amount) values(v_order.id,'custom',v_item->>'name',1,(v_item->>'amount')::bigint,(v_item->>'amount')::bigint); end loop;
  -- Transaction-local capability lets only this RPC perform the atomic completion transition.
  perform set_config('app.checkout_appointment_id',p_appointment_id::text,true);
  update public.appointments set status='completed',total_amount=v_total,custom_items=coalesce(p_custom_items,'[]') where id=p_appointment_id;
  return query select v_order.id,v_order.total_amount;
end $$;

create or replace function public.archive_appointment(p_appointment_id bigint)
returns bigint language plpgsql security invoker set search_path = pg_catalog, public as $$
declare v_appointment public.appointments; v_order public.orders; v_line record; v_resulting_stock integer; v_voided_at timestamptz;
begin
  select * into v_appointment from public.appointments where id=p_appointment_id for update;
  if not found then raise exception 'Appointment not found'; end if;
  v_voided_at:=coalesce(v_appointment.deleted_at,now());
  select * into v_order from public.orders where appointment_id=p_appointment_id for update;
  if found and v_order.voided_at is null then
    for v_line in select product_id,sum(quantity)::integer quantity from public.order_items where order_id=v_order.id and item_type='product' group by product_id order by product_id loop
      update public.products set stock=stock+v_line.quantity where id=v_line.product_id returning stock into v_resulting_stock;
      if not found then raise exception 'Product % not found while voiding order %',v_line.product_id,v_order.id; end if;
      insert into public.stock_adjustments(product_id,order_id,quantity_delta,resulting_stock,reason) values(v_line.product_id,v_order.id,v_line.quantity,v_resulting_stock,'Voided archived appointment');
    end loop;
    update public.orders set voided_at=v_voided_at,void_reason='Appointment archived' where id=v_order.id and voided_at is null;
  end if;
  update public.finance_records set voided_at=coalesce(voided_at,v_voided_at),void_reason=coalesce(void_reason,'Appointment archived'),updated_at=now()
  where appointment_id=p_appointment_id or (v_order.id is not null and order_id=v_order.id);
  update public.appointments set deleted_at=coalesce(deleted_at,v_voided_at) where id=p_appointment_id;
  return p_appointment_id;
end $$;

do $$ declare v_appointment_id bigint; begin
  for v_appointment_id in select id from public.appointments where deleted_at is not null order by id loop perform public.archive_appointment(v_appointment_id); end loop;
end $$;

-- Enable live UI refresh when this migration runs in a Supabase project.
do $$ declare t text; begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime') then
    foreach t in array array['customers','services','products','appointments','blocked_times','finance_records'] loop
      if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
        execute format('alter publication supabase_realtime add table public.%I',t);
      end if;
    end loop;
  end if;
end $$;

-- Authenticated production access. No salon data is exposed to anon.
alter table public.profiles enable row level security; alter table public.system_settings enable row level security; alter table public.customers enable row level security; alter table public.services enable row level security; alter table public.products enable row level security; alter table public.appointments enable row level security; alter table public.blocked_times enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.stock_adjustments enable row level security; alter table public.finance_records enable row level security;
do $$ declare t text; begin foreach t in array array['customers','services','products','appointments','blocked_times','orders','order_items','stock_adjustments','finance_records'] loop execute format('drop policy if exists dev_anon_all on public.%I',t); end loop; end $$;

revoke all on public.customers,public.services,public.products,public.appointments,public.blocked_times,public.orders,public.order_items,public.stock_adjustments,public.finance_records,public.system_settings from anon;
revoke usage,select on all sequences in schema public from anon;
revoke execute on function public.create_appointment(bigint,bigint,timestamptz,text,jsonb,text), public.update_appointment(bigint,bigint,bigint,timestamptz,text,jsonb,text), public.adjust_product_stock(bigint,integer,text), public.update_product(bigint,text,bigint,integer,text,boolean), public.checkout_appointment(bigint,text,jsonb,jsonb,text,bigint), public.archive_appointment(bigint) from public, anon;

do $$ declare t text; begin foreach t in array array['customers','products','appointments','blocked_times','orders','order_items','stock_adjustments','finance_records'] loop execute format('drop policy if exists authenticated_access on public.%I',t); execute format('create policy authenticated_access on public.%I for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null)',t); end loop; end $$;

drop policy if exists profiles_read_own_or_admin on public.profiles; create policy profiles_read_own_or_admin on public.profiles for select to authenticated using(id=auth.uid() or public.is_super_admin());
drop policy if exists profiles_admin_update on public.profiles; create policy profiles_admin_update on public.profiles for update to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
drop policy if exists services_read on public.services; create policy services_read on public.services for select to authenticated using(auth.uid() is not null);
drop policy if exists services_admin_insert on public.services; create policy services_admin_insert on public.services for insert to authenticated with check(public.is_super_admin());
drop policy if exists services_admin_update on public.services; create policy services_admin_update on public.services for update to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
drop policy if exists services_admin_delete on public.services; create policy services_admin_delete on public.services for delete to authenticated using(public.is_super_admin());
drop policy if exists system_settings_read on public.system_settings; create policy system_settings_read on public.system_settings for select to authenticated using(auth.uid() is not null);
drop policy if exists system_settings_admin_insert on public.system_settings; create policy system_settings_admin_insert on public.system_settings for insert to authenticated with check(public.is_super_admin());
drop policy if exists system_settings_admin_update on public.system_settings; create policy system_settings_admin_update on public.system_settings for update to authenticated using(public.is_super_admin()) with check(public.is_super_admin());
drop policy if exists system_settings_admin_delete on public.system_settings; create policy system_settings_admin_delete on public.system_settings for delete to authenticated using(public.is_super_admin());

grant select,insert,update,delete on public.customers,public.products,public.appointments,public.blocked_times,public.orders,public.order_items,public.stock_adjustments,public.finance_records to authenticated;
grant select on public.services,public.system_settings to authenticated;
grant insert,update,delete on public.services,public.system_settings to authenticated;
grant select on public.profiles to authenticated;
grant update(email,full_name,role,updated_at) on public.profiles to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.create_appointment(bigint,bigint,timestamptz,text,jsonb,text), public.update_appointment(bigint,bigint,bigint,timestamptz,text,jsonb,text), public.adjust_product_stock(bigint,integer,text), public.update_product(bigint,text,bigint,integer,text,boolean), public.checkout_appointment(bigint,text,jsonb,jsonb,text,bigint), public.archive_appointment(bigint) to authenticated;
