import { useMemo, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { CalendarDays, CreditCard, Lock, Plus, Scissors, X } from 'lucide-react';
import { addDays, format, startOfWeek } from 'date-fns';
import { api, type Appointment, type Customer, type Product, type Service } from '../../api';
import { CustomLineItemEditor } from './CustomLineItemEditor';
import type { CustomLineItem } from './types';

type Props = { appointments:Appointment[]; customers:Customer[]; services:Service[]; products:Product[]; onCreate(value:Omit<Appointment,'id'>):Promise<void>; onRefresh():Promise<void> };
const labels:Record<Appointment['status'],string>={pending:'待確認',confirmed:'已確認',in_service:'服務中',completed:'已完成',cancelled:'已取消'};
const styles:Record<Appointment['status'],string>={pending:'border-locked bg-locked-surface',confirmed:'border-confirmed bg-confirmed-surface',in_service:'border-service bg-service-surface',completed:'border-completed bg-completed-surface',cancelled:'border-slate-400 bg-slate-100'};

function CheckoutDialog({ appointment, products, onClose, onSuccess }:{appointment?:Appointment;products:Product[];onClose():void;onSuccess():Promise<void>}) {
  const [customItems,setCustomItems]=useState<CustomLineItem[]>([]); const [quantities,setQuantities]=useState<Record<number,number>>({}); const [discount,setDiscount]=useState(0); const [payment,setPayment]=useState('cash'); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
  const selectedProducts=products.filter(p=>p.id!==undefined&&(quantities[p.id]??0)>0).map(p=>({product_id:p.id!,quantity:quantities[p.id!]!}));
  const productTotal=products.reduce((sum,p)=>sum+p.price*(p.id===undefined?0:quantities[p.id]??0),0); const customTotal=customItems.reduce((sum,item)=>sum+item.amount,0); const total=Math.max(0,(appointment?.price??0)+productTotal+customTotal-discount);
  const checkout=async()=>{if(!appointment?.id)return;setSaving(true);setMessage('');try{const key=`appointment-${appointment.id}`;await api.checkoutAppointment(appointment.id,key,selectedProducts,customItems.map(({name,amount})=>({name,amount})),payment,discount);await onSuccess();onClose();}catch(error){setMessage(error instanceof Error?error.message:'結帳失敗');}finally{setSaving(false);}};
  return <Dialog.Root open={Boolean(appointment)} onOpenChange={open=>{if(!open)onClose();}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[200] bg-black/60"/><Dialog.Content className="checkout-dialog fixed inset-x-0 bottom-0 z-[201] max-h-[92vh] overflow-y-auto rounded-t-2xl bg-white p-5 shadow-panel md:inset-y-0 md:left-auto md:right-0 md:w-[480px] md:rounded-none md:p-7">
    <div className="flex justify-between"><div><Dialog.Title className="text-2xl font-black">結帳面板</Dialog.Title><Dialog.Description>庫存與訂單將由 Supabase 原子交易處理</Dialog.Description></div><Dialog.Close className="min-h-12 min-w-12" aria-label="關閉"><X className="mx-auto"/></Dialog.Close></div>
    <div className="mt-5 rounded-xl bg-salon-50 p-4"><strong>{appointment?.customerName}</strong><p>{appointment?.service_name} · {appointment&&format(new Date(appointment.start_time),'HH:mm')}</p></div>
    <div className="mt-5 space-y-3"><div className="flex justify-between"><span>服務費</span><strong>NT$ {(appointment?.price??0).toLocaleString()}</strong></div>{products.filter(p=>p.active&&p.stock_quantity>0&&p.id!==undefined).map(p=><label className="flex items-center justify-between" key={p.id}><span>{p.name}（庫存 {p.stock_quantity}）</span><input className="w-20" type="number" min="0" max={p.stock_quantity} value={quantities[p.id!]??0} onChange={e=>setQuantities(q=>({...q,[p.id!]:Math.max(0,Math.min(p.stock_quantity,Number(e.target.value)))}))}/></label>)}<CustomLineItemEditor items={customItems} onChange={setCustomItems}/><label className="block font-bold">折扣<input className="mt-1 w-full" type="number" min="0" value={discount} onChange={e=>setDiscount(Math.max(0,Number(e.target.value)))}/></label><label className="block font-bold">付款方式<select className="mt-1 w-full" value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">現金</option><option value="line_pay">LINE Pay</option></select></label><div className="flex justify-between border-t-2 pt-3 text-2xl font-black"><span>應收</span><span>NT$ {total.toLocaleString()}</span></div></div>
    {message&&<p role="alert" className="mt-3 settings-error">{message}</p>}<button disabled={saving||appointment?.status!=='in_service'} onClick={checkout} className="mt-5 min-h-14 w-full rounded-xl border border-amber-400/40 bg-amber-500 text-xl font-semibold text-slate-950 transition-colors hover:bg-amber-400 disabled:border-slate-700 disabled:bg-slate-800 disabled:text-slate-500">{saving?'處理中…':`確認收款 NT$ ${total.toLocaleString()}`}</button>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function NewBookingDialog({open,onClose,customers,services,onCreate}:{open:boolean;onClose():void;customers:Customer[];services:Service[];onCreate:Props['onCreate']}) {
 const [customerId,setCustomerId]=useState(0);const [serviceId,setServiceId]=useState(0);const [start,setStart]=useState(format(new Date(),"yyyy-MM-dd'T'HH:mm"));const [customItems,setCustomItems]=useState<CustomLineItem[]>([]);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 const close=()=>{setCustomItems([]);onClose();};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(customItems.some(item=>!item.name.trim())){setMessage('請填寫所有臨時項目名稱。');return;}setSaving(true);setMessage('');try{await onCreate({customer_id:customerId,service_id:serviceId,start_time:new Date(start).toISOString(),status:'pending',custom_items:customItems.map(({name,amount})=>({name:name.trim(),amount}))});close();}catch(error){setMessage(error instanceof Error?error.message:'新增失敗');}finally{setSaving(false);}};
 return <Dialog.Root open={open} onOpenChange={v=>{if(!v)close();}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[200] bg-black/60"/><Dialog.Content className="checkout-dialog fixed left-1/2 top-1/2 z-[201] w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 p-5"><div className="flex justify-between"><div><Dialog.Title className="text-2xl font-black">新增預約</Dialog.Title><Dialog.Description>資料會寫入目前設定的正式資料來源</Dialog.Description></div><Dialog.Close className="min-h-12 min-w-12"><X className="mx-auto"/></Dialog.Close></div><form className="mt-5 grid gap-3" onSubmit={save}><label>顧客<select required value={customerId||customers[0]?.id||''} onChange={e=>setCustomerId(Number(e.target.value))}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>服務<select required value={serviceId||services[0]?.id||''} onChange={e=>setServiceId(Number(e.target.value))}>{services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration_minutes} 分</option>)}</select></label><label>開始<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><CustomLineItemEditor items={customItems} onChange={setCustomItems}/>{message&&<p role="alert">{message}</p>}<button disabled={saving||!customers.length||!services.length} className="min-h-12 rounded-xl border border-amber-400/40 bg-amber-500 font-semibold text-slate-950 transition-colors hover:bg-amber-400">{saving?'儲存中…':'建立待確認預約'}</button></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}

export function BookingCheckoutPrototype(props:Props) {
 const [selectedDay,setSelectedDay]=useState(format(new Date(),'yyyy-MM-dd'));const [checkout,setCheckout]=useState<Appointment>();const [newOpen,setNewOpen]=useState(false);const week=useMemo(()=>Array.from({length:7},(_,i)=>addDays(startOfWeek(new Date(),{weekStartsOn:1}),i)),[]);const bookings=props.appointments.filter(a=>a.status!=='cancelled'&&format(new Date(a.start_time),'yyyy-MM-dd')===selectedDay);
 return <div className="booking-shell mx-auto max-w-7xl text-ink"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-slate-400">正式預約資料</p><h2 className="text-3xl font-black">{selectedDay}</h2></div><button onClick={()=>setNewOpen(true)} className="min-h-12 rounded-xl border border-amber-400/40 bg-amber-500 px-5 text-lg font-semibold text-slate-950 transition-colors hover:bg-amber-400"><Plus className="mr-2 inline"/>新增預約</button></header><main className="grid gap-5 md:grid-cols-[minmax(0,1fr)_minmax(300px,.8fr)]"><section className="rounded-2xl bg-white p-4 shadow-panel"><div className="mb-4 flex justify-between"><h3 className="text-2xl font-black">當日詳情 · {bookings.length} 筆</h3><Scissors/></div><div className="space-y-4">{bookings.map(a=><article key={a.id} className={`rounded-xl border-l-8 p-4 ${styles[a.status]}`}><div className="flex justify-between"><div><strong className="text-xl">{format(new Date(a.start_time),'HH:mm')}–{a.end_time&&format(new Date(a.end_time),'HH:mm')}</strong><h3 className="text-xl font-black">{a.customerName}</h3><p>{a.service_name}</p></div><span className="font-bold">{labels[a.status]}</span></div><button disabled={a.status!=='in_service'} onClick={()=>setCheckout(a)} className="mt-4 min-h-12 w-full rounded-xl border border-amber-400/40 bg-amber-500 font-semibold text-slate-950 transition-colors hover:bg-amber-400 disabled:border-slate-700 disabled:bg-slate-800 disabled:text-slate-500">{a.status==='in_service'?<><CreditCard className="mr-2 inline"/>開啟結帳</>:<><Lock className="mr-2 inline"/>需先進入服務中</>}</button></article>)}{!bookings.length&&<p>本日沒有預約。</p>}</div></section><aside className="hidden self-start rounded-2xl bg-white p-5 shadow-panel md:block"><h3 className="text-xl font-black"><CalendarDays className="mr-2 inline"/>本週</h3><div className="mt-5 grid grid-cols-7 gap-2">{week.map(day=>{const iso=format(day,'yyyy-MM-dd');const count=props.appointments.filter(a=>a.status!=='cancelled'&&a.start_time.startsWith(iso)).length;return <button key={iso} onClick={()=>setSelectedDay(iso)} className={`min-h-20 rounded-xl border-2 p-1 ${iso===selectedDay?'border-amber-500/30 bg-amber-500/10 text-amber-300':'border-slate-700 bg-slate-800/40 text-slate-400 hover:bg-slate-700/60'}`}><small>{format(day,'EEE')}</small><strong className="block">{format(day,'d')}</strong><span className="text-xs">{count}筆</span></button>})}</div></aside></main><CheckoutDialog appointment={checkout} products={props.products} onClose={()=>setCheckout(undefined)} onSuccess={props.onRefresh}/><NewBookingDialog open={newOpen} onClose={()=>setNewOpen(false)} customers={props.customers} services={props.services} onCreate={async value=>{await props.onCreate({...value,customer_id:value.customer_id||props.customers[0]?.id||0,service_id:value.service_id||props.services[0]?.id||0});}}/></div>;
}
