import { useMemo, useState } from 'react';
import { addDays, addMonths, format, isSameDay, startOfMonth, startOfWeek } from 'date-fns';
import { Appointment, AppointmentStatus, BlockTime, Customer, Product, Service } from '../api';

type View = 'month'|'week'|'day'|'list';
interface Props { appointments: Appointment[]; customers: Customer[]; products: Product[]; services: Service[]; blocks: BlockTime[]; onCreateAppointment(value: Omit<Appointment,'id'>): Promise<void>; onUpdateAppointment(value: Appointment): Promise<void>; onDeleteAppointment(id:number): Promise<void>; onCreateBlock(value: Omit<BlockTime,'id'>): Promise<void>; onDeleteBlock(id:number): Promise<void> }
const transitions: Record<AppointmentStatus, AppointmentStatus[]> = { pending:['pending','confirmed','cancelled'], confirmed:['confirmed','in_service','cancelled'], in_service:['in_service','completed','cancelled'], completed:['completed'], cancelled:['cancelled'] };
const labels: Record<AppointmentStatus,string> = { pending:'待確認',confirmed:'已確認',in_service:'服務中',completed:'已完成',cancelled:'已取消' };
const weekdayNames = ['星期日','星期一','星期二','星期三','星期四','星期五','星期六'];
const weekendClass = (dayOfWeek:number) => dayOfWeek===6?'weekend-saturday':dayOfWeek===0?'weekend-sunday':'';
const local = (value:string) => format(new Date(value), "yyyy-MM-dd'T'HH:mm");

export function CalendarView({ appointments,customers,products,services,blocks,onCreateAppointment,onUpdateAppointment,onDeleteAppointment,onCreateBlock,onDeleteBlock }:Props) {
  const mobile = window.matchMedia('(max-width: 600px)').matches;
  const [view,setView] = useState<View>(mobile?'list':window.matchMedia('(max-width: 1000px)').matches?'week':'month');
  const [date,setDate] = useState(new Date()); const [editing,setEditing] = useState<Appointment>(); const [modal,setModal] = useState<'appointment'|'block'>();
  const [customerId,setCustomerId] = useState(0); const [serviceId,setServiceId] = useState(0); const [start,setStart] = useState(''); const [status,setStatus] = useState<AppointmentStatus>('pending'); const [notes,setNotes] = useState('');
  const [productId,setProductId] = useState(0); const [blockEnd,setBlockEnd] = useState(''); const [surchargeType,setSurchargeType] = useState<'global'|'none'|'percent'|'fixed'>('global'); const [surchargeValue,setSurchargeValue] = useState(0);
  const days = useMemo(() => view==='month' ? Array.from({length:42},(_,i)=>addDays(startOfWeek(startOfMonth(date),{weekStartsOn:1}),i)) : view==='week' ? Array.from({length:7},(_,i)=>addDays(startOfWeek(date,{weekStartsOn:1}),i)) : [date],[date,view]);
  const visibleAppointments = appointments.filter(a => a.status !== 'cancelled');
  const periodApps = visibleAppointments.filter(a => days.some(d=>isSameDay(new Date(a.start_time),d)));
  const openNewAt = (selected:Date) => { const slot=new Date(selected);if(slot.getHours()===0&&slot.getMinutes()===0)slot.setHours(9,0,0,0);setDate(slot);setEditing(undefined);setCustomerId(customers[0]?.id||0);setServiceId(services[0]?.id||0);setStart(format(slot,"yyyy-MM-dd'T'HH:mm"));setStatus('pending');setNotes('');setProductId(0);setSurchargeType('global');setSurchargeValue(0);setModal('appointment'); };
  const openNew = () => openNewAt(date);
  const openEdit = (a:Appointment) => { setEditing(a);setCustomerId(a.customer_id);setServiceId(a.service_id);setStart(local(a.start_time));setStatus(a.status);setNotes(a.notes||'');setProductId(0);setSurchargeType(a.surcharge_type||'none');setSurchargeValue(a.surcharge_value||0);setModal('appointment'); };
  const move = (amount:number) => setDate(view==='month'?addMonths(date,amount):addDays(date,amount*(view==='week'?7:1)));
  const openDay = (day:Date) => { setDate(day); setView('day'); };
  const postpone = (days:number) => setStart(format(addDays(new Date(start),days),"yyyy-MM-dd'T'HH:mm"));
  async function save(event:React.FormEvent) { event.preventDefault(); const value = { customer_id:customerId,service_id:serviceId,start_time:new Date(start).toISOString(),status,notes,...(surchargeType==='global'?{}:{surcharge_type:surchargeType,surcharge_value:surchargeValue}),products:productId?[{product_id:productId,quantity:1}]:undefined }; if(editing) await onUpdateAppointment({...editing,...value}); else await onCreateAppointment(value); setModal(undefined); }
  async function saveBlock(event:React.FormEvent) { event.preventDefault(); await onCreateBlock({start_time:new Date(start).toISOString(),end_time:new Date(blockEnd).toISOString(),reason:notes});setModal(undefined); }
  return <section className="calendar-view">
    <header className="calendar-toolbar"><h2>預約行事曆</h2><button className="btn" onClick={openNew}>新增預約</button><button className="btn btn-secondary" onClick={()=>{setStart(format(date,"yyyy-MM-dd'T'HH:mm"));setBlockEnd(format(addDays(date,0),"yyyy-MM-dd'T'HH:mm"));setNotes('');setModal('block')}}>封鎖時間</button></header>
    <div className="card calendar-toolbar"><div><button onClick={()=>move(-1)}>‹</button> <b>{format(date,'yyyy / MM / dd')}（{weekdayNames[date.getDay()]}）</b> <button onClick={()=>move(1)}>›</button></div><div>{(['month','week','day','list'] as View[]).map(v=><button className={view===v?'active-view':''} key={v} onClick={()=>setView(v)}>{v==='month'?'月':v==='week'?'週':v==='day'?'日':'列表'}</button>)}</div></div>
    {(view==='day') && <div className="card day-grid">{Array.from({length:24},(_,hour)=><div className="hour" key={hour}><time>{String(hour).padStart(2,'0')}:00</time><div><button className="hour-add" onClick={()=>{const slot=new Date(date);slot.setHours(hour,0,0,0);openNewAt(slot)}}>＋ 新增預約</button>{periodApps.filter(a=>new Date(a.start_time).getHours()===hour).map(a=><AppointmentChip key={a.id} value={a} open={openEdit}/>)}</div></div>)}</div>}
    {view==='list' && <div className="card appointment-list">{periodApps.length?periodApps.map(a=><AppointmentChip key={a.id} value={a} open={openEdit}/>):<p>本日無預約</p>}{blocks.filter(b=>isSameDay(new Date(b.start_time),date)).map(b=><div key={b.id} className="block-chip">{format(new Date(b.start_time),'HH:mm')}–{format(new Date(b.end_time),'HH:mm')} {b.reason}<button onClick={()=>onDeleteBlock(b.id!)}>移除</button></div>)}</div>}
    {(view==='month'||view==='week') && <div className={`card calendar-grid ${view}`}>
      {days.slice(0,7).map(headerDate => { const dayOfWeek=headerDate.getDay(); return <div className={`calendar-weekday ${weekendClass(dayOfWeek)}`} key={headerDate.toISOString()}>{weekdayNames[dayOfWeek]}</div>; })}
      {days.map(day => { const dayOfWeek=day.getDay(); return <div className={`calendar-day ${weekendClass(dayOfWeek)}`} key={day.toISOString()}><button className="calendar-day-heading" onClick={()=>openDay(day)}><strong>{weekdayNames[dayOfWeek]}</strong><span>{format(day,'MM/dd')}</span></button><button className="calendar-add" onClick={()=>openNewAt(day)}>＋ 新增</button>{visibleAppointments.filter(a=>isSameDay(new Date(a.start_time),day)).map(a=><AppointmentChip key={a.id} value={a} open={openEdit}/>)}{blocks.filter(b=>isSameDay(new Date(b.start_time),day)).map(b=><div className="block-chip" key={b.id}>封鎖 {format(new Date(b.start_time),'HH:mm')}</div>)}</div>; })}
    </div>}
    {modal && <div className="modal-overlay"><div className="card calendar-modal"><button className="modal-close" onClick={()=>setModal(undefined)}>×</button><h3>{modal==='block'?'封鎖時間':editing?'編輯／改期':'新增預約'}</h3><form onSubmit={modal==='block'?saveBlock:save}>
      {modal==='appointment' && <><label>顧客<select required value={customerId} onChange={e=>setCustomerId(Number(e.target.value))}>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label>服務<select required value={serviceId} onChange={e=>setServiceId(Number(e.target.value))}>{services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} · {s.duration_minutes} 分 · ${s.price}</option>)}</select></label><label>商品（選填）<select value={productId} onChange={e=>setProductId(Number(e.target.value))}><option value={0}>無</option>{products.filter(p=>p.active && p.stock_quantity>0).map(p=><option key={p.id} value={p.id}>{p.name} · ${p.price} · 庫存 {p.stock_quantity}</option>)}</select></label><label>個別加價<select value={surchargeType} onChange={e=>setSurchargeType(e.target.value as typeof surchargeType)}><option value="global">使用全域假日設定</option><option value="none">無</option><option value="percent">百分比</option><option value="fixed">固定金額</option></select></label>{surchargeType!=='none'&&surchargeType!=='global'&&<label>加價值<input type="number" min="0" value={surchargeValue} onChange={e=>setSurchargeValue(Number(e.target.value))}/></label>}</>}
      {modal==='appointment'&&editing&&editing.status!=='completed'&&<div className="reschedule-actions"><span>延期／改期：</span><button type="button" onClick={()=>postpone(1)}>延後 1 日</button><button type="button" onClick={()=>postpone(7)}>延後 1 週</button></div>}<label>{modal==='appointment'?'開始時間（可直接改期）':'開始'}<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label>{modal==='block'&&<label>結束<input required type="datetime-local" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)}/></label>}{modal==='appointment'&&editing&&<label>狀態<select value={status} onChange={e=>setStatus(e.target.value as AppointmentStatus)}>{transitions[editing.status].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}<label>備註<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn" type="submit">儲存</button>{editing&&editing.status!=='completed'&&editing.status!=='cancelled'&&<button type="button" className="btn btn-secondary" onClick={async()=>{await onDeleteAppointment(editing.id!);setModal(undefined)}} title="從行事曆刪除並保留取消紀錄">刪除預約</button>}</form></div></div>}
  </section>;
}
function AppointmentChip({value,open}:{value:Appointment;open(a:Appointment):void}) { return <button className={`appointment-chip ${value.status}`} onClick={()=>open(value)}><time>{format(new Date(value.start_time),'HH:mm')}</time> {value.customerName} · {value.service_name||value.service} <small>{labels[value.status]}</small></button> }
