-- Link completed appointments/orders to the Supabase finance ledger and backfill history.
begin;

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income','expense')),
  category text not null check (btrim(category) <> ''),
  amount bigint not null check (amount >= 0),
  occurred_at timestamptz not null default now(),
  notes text,
  source text not null default 'manual' check (source in ('manual','appointment','order')),
  appointment_id bigint unique references public.appointments(id) on delete restrict,
  order_id bigint unique references public.orders(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (source = 'manual' or appointment_id is not null)
);

create index if not exists finance_records_occurred_idx on public.finance_records(occurred_at desc);
create index if not exists finance_records_type_occurred_idx on public.finance_records(type, occurred_at desc);

create or replace function public.sync_completed_appointment_income()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare v_order_id bigint; v_amount bigint; v_payment_method text; v_notes text;
begin
  if new.status <> 'completed' then return new; end if;
  select o.id,o.total_amount,o.payment_method into v_order_id,v_amount,v_payment_method
  from public.orders o where o.appointment_id=new.id;
  v_amount:=coalesce(v_amount,new.total_amount);
  v_notes:=case when v_payment_method='cash' then '現金' when v_payment_method is null then '預約完成自動入帳' else 'LINE Pay' end;
  insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
  values ('income','服務／產品銷售',v_amount,new.start_time,v_notes,case when v_order_id is null then 'appointment' else 'order' end,new.id,v_order_id)
  on conflict (appointment_id) do update
    set amount=excluded.amount,
        occurred_at=excluded.occurred_at,
        notes=excluded.notes,
        order_id=coalesce(excluded.order_id,public.finance_records.order_id),
        source=excluded.source,
        updated_at=now();
  return new;
end $$;

create or replace function public.sync_order_income()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare v_start_time timestamptz; v_notes text;
begin
  select start_time into strict v_start_time from public.appointments where id=new.appointment_id;
  v_notes:=case new.payment_method when 'cash' then '現金' else 'LINE Pay' end;
  insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
  values ('income','服務／產品銷售',new.total_amount,v_start_time,v_notes,'order',new.appointment_id,new.id)
  on conflict (appointment_id) do update
    set amount=excluded.amount,
        occurred_at=excluded.occurred_at,
        notes=excluded.notes,
        order_id=excluded.order_id,
        source='order',
        updated_at=now();
  return new;
end $$;

drop trigger if exists finance_records_updated_at on public.finance_records;
create trigger finance_records_updated_at
before update on public.finance_records
for each row execute function public.set_updated_at();

drop trigger if exists orders_sync_income on public.orders;
create trigger orders_sync_income
after insert or update of total_amount,payment_method on public.orders
for each row execute function public.sync_order_income();

drop trigger if exists appointments_sync_income on public.appointments;
create trigger appointments_sync_income
after insert or update of status,total_amount on public.appointments
for each row when (new.status = 'completed')
execute function public.sync_completed_appointment_income();

insert into public.finance_records(type,category,amount,occurred_at,notes,source,appointment_id,order_id)
select 'income','服務／產品銷售',o.total_amount,a.start_time,
  case o.payment_method when 'cash' then '現金' else 'LINE Pay' end,
  'order',a.id,o.id
from public.orders o
join public.appointments a on a.id=o.appointment_id
where a.status='completed'
on conflict (appointment_id) do update
  set amount=excluded.amount,
      occurred_at=excluded.occurred_at,
      notes=excluded.notes,
      order_id=excluded.order_id,
      source='order',
      updated_at=now();

alter table public.finance_records enable row level security;
drop policy if exists dev_anon_all on public.finance_records;
create policy dev_anon_all on public.finance_records for all to anon using (true) with check (true);
grant select,insert,update,delete on public.finance_records to anon;
grant usage,select on all sequences in schema public to anon;

do $$
begin
  if exists (select 1 from pg_publication where pubname='supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname='supabase_realtime' and schemaname='public' and tablename='finance_records'
     ) then
    alter publication supabase_realtime add table public.finance_records;
  end if;
end $$;

commit;
